name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Build SAM application
        run: |
          npm install -g aws-cdk
          sam build --use-container

      - name: Deploy SAM application
        run: |
          sam deploy --stack-name your-stack-name --region us-east-1 --capabilities CAPABILITY_IAM

      - name: Show API Gateway URL
        run: |
          aws cloudformation describe-stacks --stack-name resumetest --query 'Stacks[0].Outputs[?OutputKey==`ViewCountApi`].OutputValue' --output text
